routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HalamanController@beranda');

Route::get('verifikasi', 'HalamanController@verifikasi')->name('halaman.verifikasi');
Route::post('verifikasi', 'HalamanController@verifikasi');

Route::prefix('admin')->namespace('Auth\Admin')->group(function () {
    Route::get('masuk', 'LoginController@showLoginForm')->name('admin.masuk');
    Route::post('masuk', 'LoginController@login');

    Route::post('keluar', 'LoginController@logout')->name('admin.keluar');
});

Route::namespace('Auth\Anggota')->group(function () {
    Route::get('/oauth/google/login', 'GoogleController@login')->name('oauth.google.login');
    Route::get('/oauth/google/callback', 'GoogleController@callback')->name('oauth.google.callback');

    if (\App::isProduction() || \setting('_auth_disabled')) {
        Route::get('masuk', fn () => \redirect('/'))->name('anggota.masuk');
        Route::post('keluar', 'LoginController@logout')->name('anggota.keluar');

        return;
    }

    Route::get('daftar', 'RegisterController@showRegistrationForm')->name('anggota.daftar');
    Route::post('daftar', 'RegisterController@register');

    Route::get('masuk', 'LoginController@showLoginForm')->name('anggota.masuk');
    Route::post('masuk', 'LoginController@login');

    Route::post('keluar', 'LoginController@logout')->name('anggota.keluar');

    Route::get('password/lupa', 'ForgotPasswordController@showLinkRequestForm')
    ->name('anggota.password.lupa');

    Route::post('password/lupa', 'ForgotPasswordController@sendResetLinkEmail');

    Route::get('password/reset/{token?}', 'ResetPasswordController@showResetForm')
    ->name('anggota.password.reset');

    Route::post('password/reset/{token?}', 'ResetPasswordController@reset');

    Route::get('email/verifikasi/gagal', 'EmailVerificationController@error')
    ->name('anggota.email.verifikasi.gagal');

    Route::post('email/verifikasi/kirim', 'EmailVerificationController@resend')
    ->name('anggota.email.verifikasi.kirim');

    Route::get('email/verifikasi/cek/{id}', 'EmailVerificationController@verify')
    ->name('anggota.email.verifikasi.cek');
});

Route::prefix('admin')->middleware('auth:admin')->group(function () {
    Route::get('/', fn () => \redirect()->route('admin.dasbor'));
    Route::get('dasbor', 'AdminController@dasbor')->name('admin.dasbor');

    Route::get('pengaturan', 'AdminController@pengaturan')->name('admin.pengaturan');
    Route::post('pengaturan', 'AdminController@pengaturan');

    Route::prefix('muzaki')->group(function () {
        Route::get('', 'AdminController@muzaki')->name('admin.muzaki');

        Route::get('templat', 'AdminController@muzaki_templat')->name('admin.muzaki_templat');
        Route::get('ekspor', 'AdminController@muzaki_ekspor')->name('admin.muzaki_ekspor');
        Route::get('impor', 'AdminController@muzaki_impor')->name('admin.muzaki_impor');
        Route::post('impor', 'AdminController@muzaki_impor');

        Route::get('lihat/{muzaki}', 'AdminController@muzaki_lihat')->name('admin.muzaki_lihat');
        Route::get('masuk/{muzaki}', 'AdminController@muzaki_masuk')->name('admin.muzaki_masuk');

        Route::get('edit/{muzaki}', 'AdminController@muzaki_edit')->name('admin.muzaki_edit');
        Route::post('edit/{muzaki}', 'AdminController@muzaki_edit');

        Route::post('hapus/{muzaki}', 'AdminController@muzaki_hapus')->name('admin.muzaki_hapus');
    });

    Route::prefix('mustahik')->group(function () {
        Route::get('', 'AdminController@mustahik')->name('admin.mustahik');

        Route::get('templat', 'AdminController@mustahik_templat')->name('admin.mustahik_templat');
        Route::get('ekspor', 'AdminController@mustahik_ekspor')->name('admin.mustahik_ekspor');
        Route::get('impor', 'AdminController@mustahik_impor')->name('admin.mustahik_impor');
        Route::post('impor', 'AdminController@mustahik_impor');

        Route::get('tambah', 'AdminController@mustahik_tambah')->name('admin.mustahik_tambah');
        Route::post('tambah', 'AdminController@mustahik_tambah');

        Route::get('lihat/{mustahik}', 'AdminController@mustahik_lihat')->name('admin.mustahik_lihat');

        Route::get('edit/{mustahik}', 'AdminController@mustahik_edit')->name('admin.mustahik_edit');
        Route::post('edit/{mustahik}', 'AdminController@mustahik_edit');

        Route::post('hapus/{mustahik}', 'AdminController@mustahik_hapus')->name('admin.mustahik_hapus');
    });

    Route::prefix('donasi')->group(function () {
        Route::get('', 'AdminController@donasi')->name('admin.donasi');

        Route::get('templat', 'AdminController@donasi_templat')->name('admin.donasi_templat');
        Route::get('ekspor', 'AdminController@donasi_ekspor')->name('admin.donasi_ekspor');
        Route::get('impor', 'AdminController@donasi_impor')->name('admin.donasi_impor');
        Route::post('impor', 'AdminController@donasi_impor');

        Route::get('lihat/{donasi}', 'AdminController@donasi_lihat')->name('admin.donasi_lihat');

        Route::get('edit/{donasi}', 'AdminController@donasi_edit')->name('admin.donasi_edit');
        Route::post('edit/{donasi}', 'AdminController@donasi_edit');

        Route::post('hapus/{donasi}', 'AdminController@donasi_hapus')->name('admin.donasi_hapus');
    });

    Route::prefix('distribusi')->group(function () {
        Route::get('', 'AdminController@distribusi')->name('admin.distribusi');

        Route::get('templat', 'AdminController@distribusi_templat')->name('admin.distribusi_templat');
        Route::get('ekspor', 'AdminController@distribusi_ekspor')->name('admin.distribusi_ekspor');
        Route::get('impor', 'AdminController@distribusi_impor')->name('admin.distribusi_impor');
        Route::post('impor', 'AdminController@distribusi_impor');

        Route::get('lihat/{distribusi}', 'AdminController@distribusi_lihat')->name('admin.distribusi_lihat');

        Route::get('edit/{distribusi}', 'AdminController@distribusi_edit')->name('admin.distribusi_edit');
        Route::post('edit/{distribusi}', 'AdminController@distribusi_edit');

        Route::post('hapus/{distribusi}', 'AdminController@distribusi_hapus')->name('admin.distribusi_hapus');
    });

    Route::prefix('log')->group(function () {
        Route::get('', 'AdminController@log')->name('admin.log');
        Route::post('tambah', 'AdminController@log_tambah')->name('admin.log_tambah');
        Route::get('lihat/{log}', 'AdminController@log_lihat')->name('admin.log_lihat');
    });
});

Route::middleware('auth:anggota')->group(function () {
    Route::get('dasbor', fn () => \redirect()->route('anggota.donasi'))->name('anggota.dasbor');

    Route::get('profil', 'AnggotaController@profil')->name('anggota.profil');
    Route::post('profil', 'AnggotaController@profil');

    Route::get('donasi', 'AnggotaController@donasi')->name('anggota.donasi');

    Route::get('distribusi', 'AnggotaController@distribusi')->name('anggota.distribusi');
});

app/Models/Donasi.php
<?php

namespace App\Models;

use App\Enums\DonasiStatus;
use App\Model;
use App\Models\Muzaki;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Validation\Rule;
use Illuminate\Validation\ValidationException;

class Donasi extends Model
{
    use HasFactory;

    protected $table = 'donasi';

    protected $fillable = [
        // 'id',
        // 'id_muzaki',
        'tanggal',
        'status',
        'zakat',
        'infak',
        'santunan',
        'wakaf',
        'jumlah',
        'keterangan',
        'link_kuitansi',
        // 'detail',
        // 'created_at',
        // 'updated_at',
    ];

    protected $attributes = [
        'detail' => '{}',
        'zakat' => 0,
        'infak' => 0,
        'santunan' => 0,
        'wakaf' => 0,
    ];

    protected $casts = [
        'tanggal' => 'datetime',
        'status' => 'integer',
        'zakat' => 'integer',
        'infak' => 'integer',
        'santunan' => 'integer',
        'wakaf' => 'integer',
        'jumlah' => 'integer',
        'detail' => 'object',
    ];

    public function muzaki()
    {
        return $this->belongsTo(Muzaki::class, 'id_muzaki');
    }

    protected function getData(): array
    {
        return array_merge($this->getAttributes(), [
            'detail' => json_decode($this->attributes['detail'], true),
        ]);
    }

    protected function getRules(): array
    {
        return [
            'tanggal' => 'required|date',
            'status' => [
                'required',
                Rule::in(DonasiStatus::getValues()),
            ],
            'zakat' => 'required|integer|min:0|max:4294967295',
            'infak' => 'required|integer|min:0|max:4294967295',
            'santunan' => 'required|integer|min:0|max:4294967295',
            'wakaf' => 'required|integer|min:0|max:4294967295',
            'jumlah' => [
                'required',
                'integer',
                'min:0',
                'max:4294967295',
                Rule::in([$this->getJumlah()]),
            ],
            'link_kuitansi' => 'nullable|url|max:255',
            'keterangan' => 'nullable|string|max:65535',
            'detail' => 'object',
            'detail' => 'present|array',
        ];
    }

    public function getStatusEnumAttribute(): ?DonasiStatus
    {
        return DonasiStatus::coerce($this->status);
    }

    public function getStatusTextAttribute(): string
    {
        return DonasiStatus::getDescription($this->status);
    }

    public function setTanggalAttribute($tanggal)
    {
        if (is_string($tanggal)) {
            $tanggal = str_replace('/', '-', $tanggal);
            $tanggal = str_replace('.', ':', $tanggal);

            $formats = [
                'Y-m-d',
                'Y-m-d H:i',
                'Y-m-d H:i:s',
                'd-m-Y',
                'd-m-Y H:i',
                'd-m-Y H:i:s',
            ];

            $valid = false;

            foreach ($formats as $format) {
                $validator = \Validator::make(compact('tanggal'), [
                    'tanggal' => "date_format:$format",
                ]);

                if ($validator->passes()) {
                    $valid = true;
                    break;
                }
            }

            if (!$valid) {
                \Validator::validate(compact('tanggal'), [
                    'tanggal' => "date_format:{$formats[0]}",
                ]);
            }

            $tanggal = Carbon::parse($tanggal)->format('Y-m-d H:i:s');
        }

        $this->attributes['tanggal'] = $tanggal;
    }

    public function setStatusAttribute($status)
    {
        if (is_numeric($status)) {
            $status = (int) $status;
        } elseif (is_string($status)) {
            $patterns = [
                '/proses/i' => DonasiStatus::AutodebitProses,
                '/tidak.*berhasil/i' => DonasiStatus::AutodebitGagal,
                '/berhasil/i' => DonasiStatus::AutodebitBerhasil,
                '/gagal/i' => DonasiStatus::AutodebitGagal,
                '/belum.*nis/i' => DonasiStatus::AutodebitBelumNisab,
                '/belum.*daf/i' => DonasiStatus::BelumTerdaftar,
                '/transfer/i' => DonasiStatus::TransferRekening,
                '/tunai/i' => DonasiStatus::TunaiKasir,
            ];

            foreach ($patterns as $pattern => $value) {
                if (preg_match($pattern, $status)) {
                    $status = $value;
                    break;
                }
            }

            if (is_string($status)) {
                $status = \Str::studly($status);
            }
        }

        $status = DonasiStatus::coerce($status);

        if ($status === null) {
            throw ValidationException::withMessages([
                'status' => 'Status tidak valid',
            ]);
        }

        $this->attributes['status'] = $status->value;
    }

    public function getJumlah(): int
    {
        return $this->zakat + $this->infak + $this->santunan + $this->wakaf;
    }

    public function setJumlah(): void
    {
        $this->jumlah = $this->getJumlah();
    }

    public function scopeBerhasil($query)
    {
        return $query->whereIn('status', DonasiStatus::Berhasil());
    }
}

app/Models/Pengguna.php
<?php

namespace App\Models;

use App\Models\Admin;
use App\Models\Anggota;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Http\UploadedFile;
use Illuminate\Notifications\Notifiable;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Validator;

class Pengguna extends Authenticatable
{
    use Notifiable;

    public const FOTO_DIR = '';
    public const FOTO_DEFAULT = '_default.png';

    protected $fillable = [
        // 'id',
        'nama',
        'email',
        'password',
        // 'remember_token',
        // 'created_at',
        // 'updated_at',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected function getRules(): array
    {
        return [
            'nama' => 'required|string|max:191',
            'email' => [
                'required',
                'email',
                'max:191',
                Rule::unique($this->table)->ignore($this->id),
            ],
            'password' => 'required|string|max:191',
            'foto' => 'nullable|string|max:191',
        ];
    }

    protected function getData(): array
    {
        return $this->getAttributes();
    }

    public function getValidator(): Validator
    {
        return \Validator::make($this->getData(), $this->getRules());
    }

    public function save(array $options = []): bool
    {
        $this->getValidator()->validate();

        $foto_old = $this->getOriginal('foto');

        $save = parent::save($options);

        if (!$this->wasRecentlyCreated && $this->wasChanged('foto')) {
            $this->unlinkFotoOld($foto_old);
        }

        return $save;
    }

    public function getFotoUrlAttribute(): string
    {
        $dir = static::FOTO_DIR;
        $file = $this->attributes['foto'] ?? static::FOTO_DEFAULT;

        return \Storage::disk('public')->url("$dir/$file");
    }

    public function setFotoAttribute($foto): void
    {
        if ($foto instanceof UploadedFile) {
            \Validator::make(compact('foto'), [
                'foto' => 'image|max:5000',
            ])->validate();

            $id = (int) $this->id;
            $uuid = (string) \Str::orderedUuid();
            $extension = $foto->extension();
            $name = "$id--$uuid.$extension";
            $dir = static::FOTO_DIR;

            \Storage::disk('public')->putFileAs($dir, $foto, $name);

            $this->attributes['foto'] = $name;
        } elseif (is_string($foto)) {
            $this->attributes['foto'] = $foto;
        }
    }

    public function unlinkFotoOld(): void
    {
        $dir = static::FOTO_DIR;
        $file = $this->changes['foto'];

        if (empty($file) || $file === static::FOTO_DEFAULT) {
            return;
        }

        \Storage::disk('public')->delete("$dir/$file");
    }

    public function isAdmin(): bool
    {
        return $this instanceof Admin;
    }

    public function isAnggota(): bool
    {
        return $this instanceof Anggota;
    }
}

resources/views/admin-donasi-lihat.blade.php
@extends ('layouts.argon.dashboard')

@section ('content')
<div class="header pb-6 pb-xl-5 pt-8 d-flex align-items-center">
  <span class="mask bg-gradient-primary opacity-8"></span>
</div>
<div class="container-fluid mt--7 mt-lg--6 mb-3">
  <div class="row">
    <div class="col-12 mx-auto">
      <div class="card shadow h-100">
        <div class="card-header">
          <h2 class="mb-0">
            Donasi: #{{ $donasi->id }}
          </h2>
        </div>

        <div class="card-body">
          @messages

          @push('js')
            <script>
              $('.form-control-plaintext.number').addClass('text-right text-monospace');
              $('#jumlah').addClass('text-primary').css('font-size', 'larger');
            </script>
          @endpush

          <form autocomplete="off" method="post" action="{{ url()->current() }}" id="form">
            @csrf
            <div class="row no-gutters">
              <div class="col-xl-6 mb-3 d-flex flex-column pb-1">
                <div class="form-group row">
                  <label class="col-md-4 col-xl-5 col-form-label text-md-right font-weight-bold">
                    Nama
                  </label>
                  <div class="col-md-8 col-xl-7">
                    <input type="text" class="form-control-plaintext" id="nama" name="nama"
                      value="{{ $muzaki->nama }}" disabled>
                  </div>
                </div>

                <div class="form-group row">
                  <label class="col-md-4 col-xl-5 col-form-label text-md-right font-weight-bold">
                    NIP
                  </label>
                  <div class="col-md-8 col-xl-7">
                    <input type="text" class="form-control-plaintext" id="nip" name="nip"
                      value="{{ $muzaki->nip }}" disabled>
                  </div>
                </div>

                <div class="form-group row">
                  <label class="col-md-4 col-xl-5 col-form-label text-md-right font-weight-bold">
                    Tanggal
                  </label>
                  <div class="col-md-8 col-xl-7">
                    <input type="text" class="form-control-plaintext" id="tanggal" name="tanggal"
                      value="{{ $donasi->tanggal }}" disabled>
                  </div>
                </div>

                <div class="form-group row">
                  <label class="col-md-4 col-xl-5 col-form-label text-md-right font-weight-bold">
                    Status
                  </label>
                  <div class="col-md-8 col-xl-7">
                    <input type="text" class="form-control-plaintext" id="status" name="status"
                      value="{{ $donasi->status_text }}" disabled>
                  </div>
                </div>
              </div>

              <div class="col-xl-6 mb-3 d-flex flex-column pb-1">
                <div class="form-group row">
                  <label class="col-md-4 col-xl-5 col-form-label text-md-right font-weight-bold">
                    Zakat
                  </label>
                  <div class="col-md-8 col-xl-7">
                    <input type="text" class="form-control-plaintext number" id="zakat" name="zakat"
                      value="{{ format_rupiah($donasi->zakat) }}" disabled>
                  </div>
                </div>

                <div class="form-group row">
                  <label class="col-md-4 col-xl-5 col-form-label text-md-right font-weight-bold">
                    Infak
                  </label>
                  <div class="col-md-8 col-xl-7">
                    <input type="text" class="form-control-plaintext number" id="infak" name="infak"
                      value="{{ format_rupiah($donasi->infak) }}" disabled>
                  </div>
                </div>

                <div class="form-group row">
                  <label class="col-md-4 col-xl-5 col-form-label text-md-right font-weight-bold">
                    Santunan Yatim
                  </label>
                  <div class="col-md-8 col-xl-7">
                    <input type="text" class="form-control-plaintext number" id="santunan"
                      name="santunan" value="{{ format_rupiah($donasi->santunan) }}" disabled>
                  </div>
                </div>

                <div class="form-group row">
                  <label class="col-md-4 col-xl-5 col-form-label text-md-right font-weight-bold">
                    Wakaf Tunai
                  </label>
                  <div class="col-md-8 col-xl-7">
                    <input type="text" class="form-control-plaintext number" id="wakaf"
                      name="wakaf" value="{{ format_rupiah($donasi->wakaf) }}" disabled>
                  </div>
                </div>

                <div class="form-group row">
                  <label class="col-md-4 col-xl-5 col-form-label text-md-right font-weight-bold">
                    Jumlah
                  </label>
                  <div class="col-md-8 col-xl-7">
                    <input type="text" class="form-control-plaintext number" id="jumlah"
                      name="jumlah" value="{{ format_rupiah($donasi->jumlah) }}" disabled>
                  </div>
                </div>
              </div>
            </div>

            <hr class="mt-0">

            <div class="row">
              <div class="col-lg-8">
                <div class="form-group row">
                  <label class="col-md-5 col-form-label text-md-right font-weight-bold">
                    Keterangan
                  </label>
                  <div class="col-md-7 my-2">
                    {!! nl2br(e($donasi->keterangan)) !!}
                  </div>
                </div>
              </div>
            </div>

            @if ($link_kuitansi = $donasi->link_kuitansi)
              <hr class="mt-0">

              <div class="row">
                <div class="col-lg-8">
                  <div class="form-group row">
                    <label class="col-md-5 text-md-right font-weight-bold">
                      Link Kuitansi
                    </label>
                    <div class="col-md-7">
                      <a href="{{ $link_kuitansi }}">
                        {{ $link_kuitansi }}
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            @endif

            <hr class="mt-0">

            <div class="row">
              <div class="col-lg-3 col-md-4 mx-auto my-1">
                <a href="{{ route('admin.donasi_edit', $donasi) }}" class="btn btn-block btn-dark">
                  Edit
                </a>
              </div>

              <div class="col-lg-3 col-md-4 mx-auto my-1">
                <a href="{{ route('admin.dasbor') }}" class="btn btn-block btn-secondary">
                  Kembali
                </a>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/anggota-mustahik-lihat.blade.php
@extends('layouts.argon.dashboard')

@section ('content')

<div class="header pb-2 pb-xl-4 pt-8 d-flex align-items-center"></div>

<div class="container-fluid mt--5">
  <div class="row">
    <div class="col-12">
      <div class="card shadow h-100">
        <div class="card-header">
          <h3 class="mb-0">
            Profil Mustahik
          </h3>
        </div>
        <div class="card-body">
          @messages

          <div class="row no-gutters">
            <div class="col-lg-3 col-md-6 mx-auto mb-3 d-flex flex-column pb-1">
              <div class="row">
                <div class="col-lg-10 mx-auto">
                  <div class="">
                    <div class="p-3 text-center">
                      <img src="{{ $mustahik->foto_url }}" class="border shadow mw-100">
                    </div>
                  </div>

                  <ul class="list-group mt-1" style="font-size: smaller;">
                    <li class="list-group-item">
                      <div class="row no-gutters">
                        <div class="col-4 font-weight-bold">
                          NIK
                        </div>
                        <div class="col">
                          {{ $mustahik->nik_masked }}
                        </div>
                      </div>
                    </li>

                    <li class="list-group-item">
                      <div class="row no-gutters">
                        <div class="col-4 font-weight-bold">
                          NRP
                        </div>
                        <div class="col">
                          {{ $mustahik->nrp ?? '-' }}
                        </div>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
            </div>

            <div class="w-100 d-lg-none"></div>

            <div class="col">
              <ul class="list-group">
                <li class="list-group-item">
                  <div class="row">
                    <div class="col-lg-3 col-6 font-weight-bold">
                      Nama Lengkap
                    </div>
                    <div class="col">
                      {{ $mustahik->nama }}
                    </div>
                  </div>
                </li>

                <li class="list-group-item">
                  <div class="row">
                    <div class="col-lg-3 col-6 font-weight-bold">
                      Asnaf
                    </div>
                    <div class="col">
                      {{ $mustahik->asnaf_text }}
                    </div>
                  </div>
                </li>

                <li class="list-group-item">
                  <div class="row">
                    <div class="col-lg-3 col-6 font-weight-bold">
                      Kab./Kota
                    </div>
                    <div class="col">
                      {{ $mustahik->nama_kota }}
                    </div>
                  </div>
                </li>

                <li class="list-group-item">
                  <div class="row">
                    <div class="col-lg-3 col-6 font-weight-bold">
                      Provinsi
                    </div>
                    <div class="col">
                      {{ $mustahik->nama_provinsi }}
                    </div>
                  </div>
                </li>
              </ul>

              <div class="row my-3">
                <div class="col-lg-12 mx-auto">
                  <div class="card shadow h-100">
                    <div class="card-header">
                      <h3 class="mb-0">
                        Bantuan Diterima
                      </h3>
                    </div>
                    <div class="table-responsive" style="max-height: 52vh;">
                      <table class="table" id="table_bantuan">
                        <thead class="thead-light">
                          <tr>
                            <th>Tanggal</th>
                            <th>Bantuan</th>
                            <th class="text-right">Nominal</th>
                          </tr>
                        </thead>
                        <tbody>
                          @forelse ($mustahik->distribusi as $distribusi)
                            <tr>
                              <td>
                                {{ $distribusi->tanggal->isoFormat('MMM YYYY') }}
                              </td>
                              <td>
                                {{ $distribusi->item }}
                              </td>
                              <td class="text-right font-weight-bold">
                                {{ format_number($distribusi->nominal) }}
                              </td>
                            </tr>

                            @if ($loop->last)
                              <tr>
                                <th colspan="2" scope="row" class="font-weight-bold text-primary">
                                  Total
                                </th>
                                <td class="text-right font-weight-bold text-primary">
                                  {{ format_rupiah($mustahik->distribusi()->sum('nominal')) }}
                                </td>
                              </tr>
                            @endif
                          @empty
                            <tr>
                              <td colspan="3" class="text-center">
                                Belum ada data.
                              </td>
                            </tr>
                          @endforelse
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

@push ('css')
<link rel="stylesheet" href="//unpkg.com/scroll-hint@latest/css/scroll-hint.css" crossorigin>
@endpush

@push ('js')
<script src="//unpkg.com/scroll-hint@latest/js/scroll-hint.min.js" crossorigin></script>
<script>
  table = $('#table_bantuan');
  table_width = table.width();
  wrapper_width = table.parent().parent().width();

  if (table_width / wrapper_width > 1.2) {
    new ScrollHint(table.closest('.table-responsive'), {
      i18n: { scrollable: 'Swipe' },
    });
  }
</script>
@endpush

resources/views/halaman-beranda.blade.php
@extends ('layouts.argon.dashboard')

@section ('content')

@include ('layouts.argon.inc.header-guest')

<div class="container mt--8 mb--1">
  <div class="row mt--2 justify-content-center">
    <div class="col-lg-5 col-md-7">
      <div class="card bg-secondary shadow border-0">
        <div class="card-header bg-transparent">
          <h1 class="text-center">Masuk sebagai Muzaki</h1>
        </div>
        <div class="px-3 pt-3">
          @messages
        </div>
        <div class="card-body px-lg-5 pt-0 pb-0 text-center">
          <img src="{{ asset('assets/img/brand/favicon.png') }}" style="max-height: 100px;">

          <p class="my-3">
            Selamat datang di Unit Pengumpul Zakat IPB.
            Silakan masuk dengan Email IPB.
          </p>
        </div>
        <div class="card-footer bg-transparent text-center">
          <a href="{{ route('oauth.google.login') }}" class="btn btn-block btn-primary">
            Masuk
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

@push ('js')
  <script>
    $('.password-toggle').click(function() {
      inputGroup = $(this).closest('.input-group');
      input = $(inputGroup).find('input');
      input.attr('type', (input.attr('type') === 'text') ? 'password' : 'text');
      input.next().find('i').toggleClass('d-none');
    });
  </script>
@endpush