routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HalamanController@beranda');

Route::get('verifikasi', 'HalamanController@verifikasi')->name('halaman.verifikasi');
Route::post('verifikasi', 'HalamanController@verifikasi');

Route::prefix('admin')->namespace('Auth\Admin')->group(function () {
    Route::get('masuk', 'LoginController@showLoginForm')->name('admin.masuk');
    Route::post('masuk', 'LoginController@login');

    Route::post('keluar', 'LoginController@logout')->name('admin.keluar');
});

Route::namespace('Auth\Anggota')->group(function () {
    Route::get('/oauth/google/login', 'GoogleController@login')->name('oauth.google.login');
    Route::get('/oauth/google/callback', 'GoogleController@callback')->name('oauth.google.callback');

    if (\App::isProduction() || \setting('_auth_disabled')) {
        Route::get('masuk', fn () => \redirect('/'))->name('anggota.masuk');
        Route::post('keluar', 'LoginController@logout')->name('anggota.keluar');

        return;
    }

    Route::get('daftar', 'RegisterController@showRegistrationForm')->name('anggota.daftar');
    Route::post('daftar', 'RegisterController@register');

    Route::get('masuk', 'LoginController@showLoginForm')->name('anggota.masuk');
    Route::post('masuk', 'LoginController@login');

    Route::post('keluar', 'LoginController@logout')->name('anggota.keluar');

    Route::get('password/lupa', 'ForgotPasswordController@showLinkRequestForm')
    ->name('anggota.password.lupa');

    Route::post('password/lupa', 'ForgotPasswordController@sendResetLinkEmail');

    Route::get('password/reset/{token?}', 'ResetPasswordController@showResetForm')
    ->name('anggota.password.reset');

    Route::post('password/reset/{token?}', 'ResetPasswordController@reset');

    Route::get('email/verifikasi/gagal', 'EmailVerificationController@error')
    ->name('anggota.email.verifikasi.gagal');

    Route::post('email/verifikasi/kirim', 'EmailVerificationController@resend')
    ->name('anggota.email.verifikasi.kirim');

    Route::get('email/verifikasi/cek/{id}', 'EmailVerificationController@verify')
    ->name('anggota.email.verifikasi.cek');
});

Route::prefix('admin')->middleware('auth:admin')->group(function () {
    Route::get('/', fn () => \redirect()->route('admin.dasbor'));
    Route::get('dasbor', 'AdminController@dasbor')->name('admin.dasbor');

    Route::get('pengaturan', 'AdminController@pengaturan')->name('admin.pengaturan');
    Route::post('pengaturan', 'AdminController@pengaturan');

    Route::prefix('muzaki')->group(function () {
        Route::get('', 'AdminController@muzaki')->name('admin.muzaki');

        Route::get('templat', 'AdminController@muzaki_templat')->name('admin.muzaki_templat');
        Route::get('ekspor', 'AdminController@muzaki_ekspor')->name('admin.muzaki_ekspor');
        Route::get('impor', 'AdminController@muzaki_impor')->name('admin.muzaki_impor');
        Route::post('impor', 'AdminController@muzaki_impor');

        Route::get('lihat/{muzaki}', 'AdminController@muzaki_lihat')->name('admin.muzaki_lihat');
        Route::get('masuk/{muzaki}', 'AdminController@muzaki_masuk')->name('admin.muzaki_masuk');

        Route::get('edit/{muzaki}', 'AdminController@muzaki_edit')->name('admin.muzaki_edit');
        Route::post('edit/{muzaki}', 'AdminController@muzaki_edit');

        Route::post('hapus/{muzaki}', 'AdminController@muzaki_hapus')->name('admin.muzaki_hapus');
    });

    Route::prefix('mustahik')->group(function () {
        Route::get('', 'AdminController@mustahik')->name('admin.mustahik');

        Route::get('templat', 'AdminController@mustahik_templat')->name('admin.mustahik_templat');
        Route::get('ekspor', 'AdminController@mustahik_ekspor')->name('admin.mustahik_ekspor');
        Route::get('impor', 'AdminController@mustahik_impor')->name('admin.mustahik_impor');
        Route::post('impor', 'AdminController@mustahik_impor');

        Route::get('tambah', 'AdminController@mustahik_tambah')->name('admin.mustahik_tambah');
        Route::post('tambah', 'AdminController@mustahik_tambah');

        Route::get('lihat/{mustahik}', 'AdminController@mustahik_lihat')->name('admin.mustahik_lihat');

        Route::get('edit/{mustahik}', 'AdminController@mustahik_edit')->name('admin.mustahik_edit');
        Route::post('edit/{mustahik}', 'AdminController@mustahik_edit');

        Route::post('hapus/{mustahik}', 'AdminController@mustahik_hapus')->name('admin.mustahik_hapus');
    });

    Route::prefix('donasi')->group(function () {
        Route::get('', 'AdminController@donasi')->name('admin.donasi');

        Route::get('templat', 'AdminController@donasi_templat')->name('admin.donasi_templat');
        Route::get('ekspor', 'AdminController@donasi_ekspor')->name('admin.donasi_ekspor');
        Route::get('impor', 'AdminController@donasi_impor')->name('admin.donasi_impor');
        Route::post('impor', 'AdminController@donasi_impor');

        Route::get('lihat/{donasi}', 'AdminController@donasi_lihat')->name('admin.donasi_lihat');

        Route::get('edit/{donasi}', 'AdminController@donasi_edit')->name('admin.donasi_edit');
        Route::post('edit/{donasi}', 'AdminController@donasi_edit');

        Route::post('hapus/{donasi}', 'AdminController@donasi_hapus')->name('admin.donasi_hapus');
    });

    Route::prefix('distribusi')->group(function () {
        Route::get('', 'AdminController@distribusi')->name('admin.distribusi');

        Route::get('templat', 'AdminController@distribusi_templat')->name('admin.distribusi_templat');
        Route::get('ekspor', 'AdminController@distribusi_ekspor')->name('admin.distribusi_ekspor');
        Route::get('impor', 'AdminController@distribusi_impor')->name('admin.distribusi_impor');
        Route::post('impor', 'AdminController@distribusi_impor');

        Route::get('lihat/{distribusi}', 'AdminController@distribusi_lihat')->name('admin.distribusi_lihat');

        Route::get('edit/{distribusi}', 'AdminController@distribusi_edit')->name('admin.distribusi_edit');
        Route::post('edit/{distribusi}', 'AdminController@distribusi_edit');

        Route::post('hapus/{distribusi}', 'AdminController@distribusi_hapus')->name('admin.distribusi_hapus');
    });

    Route::prefix('log')->group(function () {
        Route::get('', 'AdminController@log')->name('admin.log');
        Route::post('tambah', 'AdminController@log_tambah')->name('admin.log_tambah');
        Route::get('lihat/{log}', 'AdminController@log_lihat')->name('admin.log_lihat');
    });
});

Route::middleware('auth:anggota')->group(function () {
    Route::get('dasbor', fn () => \redirect()->route('anggota.donasi'))->name('anggota.dasbor');

    Route::get('profil', 'AnggotaController@profil')->name('anggota.profil');
    Route::post('profil', 'AnggotaController@profil');

    Route::get('donasi', 'AnggotaController@donasi')->name('anggota.donasi');

    Route::get('distribusi', 'AnggotaController@distribusi')->name('anggota.distribusi');
});

app/Models/Donasi.php
<?php

namespace App\Models;

use App\Enums\DonasiStatus;
use App\Model;
use App\Models\Muzaki;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Validation\Rule;
use Illuminate\Validation\ValidationException;

class Donasi extends Model
{
    use HasFactory;

    protected $table = 'donasi';

    protected $fillable = [
        // 'id',
        // 'id_muzaki',
        'tanggal',
        'status',
        'zakat',
        'infak',
        'santunan',
        'wakaf',
        'jumlah',
        'keterangan',
        'link_kuitansi',
        // 'detail',
        // 'created_at',
        // 'updated_at',
    ];

    protected $attributes = [
        'detail' => '{}',
        'zakat' => 0,
        'infak' => 0,
        'santunan' => 0,
        'wakaf' => 0,
    ];

    protected $casts = [
        'tanggal' => 'datetime',
        'status' => 'integer',
        'zakat' => 'integer',
        'infak' => 'integer',
        'santunan' => 'integer',
        'wakaf' => 'integer',
        'jumlah' => 'integer',
        'detail' => 'object',
    ];

    public function muzaki()
    {
        return $this->belongsTo(Muzaki::class, 'id_muzaki');
    }

    protected function getData(): array
    {
        return array_merge($this->getAttributes(), [
            'detail' => json_decode($this->attributes['detail'], true),
        ]);
    }

    protected function getRules(): array
    {
        return [
            'tanggal' => 'required|date',
            'status' => [
                'required',
                Rule::in(DonasiStatus::getValues()),
            ],
            'zakat' => 'required|integer|min:0|max:4294967295',
            'infak' => 'required|integer|min:0|max:4294967295',
            'santunan' => 'required|integer|min:0|max:4294967295',
            'wakaf' => 'required|integer|min:0|max:4294967295',
            'jumlah' => [
                'required',
                'integer',
                'min:0',
                'max:4294967295',
                Rule::in([$this->getJumlah()]),
            ],
            'link_kuitansi' => 'nullable|url|max:255',
            'keterangan' => 'nullable|string|max:65535',
            'detail' => 'object',
            'detail' => 'present|array',
        ];
    }

    public function getStatusEnumAttribute(): ?DonasiStatus
    {
        return DonasiStatus::coerce($this->status);
    }

    public function getStatusTextAttribute(): string
    {
        return DonasiStatus::getDescription($this->status);
    }

    public function setTanggalAttribute($tanggal)
    {
        if (is_string($tanggal)) {
            $tanggal = str_replace('/', '-', $tanggal);
            $tanggal = str_replace('.', ':', $tanggal);

            $formats = [
                'Y-m-d',
                'Y-m-d H:i',
                'Y-m-d H:i:s',
                'd-m-Y',
                'd-m-Y H:i',
                'd-m-Y H:i:s',
            ];

            $valid = false;

            foreach ($formats as $format) {
                $validator = \Validator::make(compact('tanggal'), [
                    'tanggal' => "date_format:$format",
                ]);

                if ($validator->passes()) {
                    $valid = true;
                    break;
                }
            }

            if (!$valid) {
                \Validator::validate(compact('tanggal'), [
                    'tanggal' => "date_format:{$formats[0]}",
                ]);
            }

            $tanggal = Carbon::parse($tanggal)->format('Y-m-d H:i:s');
        }

        $this->attributes['tanggal'] = $tanggal;
    }

    public function setStatusAttribute($status)
    {
        if (is_numeric($status)) {
            $status = (int) $status;
        } elseif (is_string($status)) {
            $patterns = [
                '/proses/i' => DonasiStatus::AutodebitProses,
                '/tidak.*berhasil/i' => DonasiStatus::AutodebitGagal,
                '/berhasil/i' => DonasiStatus::AutodebitBerhasil,
                '/gagal/i' => DonasiStatus::AutodebitGagal,
                '/belum.*nis/i' => DonasiStatus::AutodebitBelumNisab,
                '/belum.*daf/i' => DonasiStatus::BelumTerdaftar,
                '/transfer/i' => DonasiStatus::TransferRekening,
                '/tunai/i' => DonasiStatus::TunaiKasir,
            ];

            foreach ($patterns as $pattern => $value) {
                if (preg_match($pattern, $status)) {
                    $status = $value;
                    break;
                }
            }

            if (is_string($status)) {
                $status = \Str::studly($status);
            }
        }

        $status = DonasiStatus::coerce($status);

        if ($status === null) {
            throw ValidationException::withMessages([
                'status' => 'Status tidak valid',
            ]);
        }

        $this->attributes['status'] = $status->value;
    }

    public function getJumlah(): int
    {
        return $this->zakat + $this->infak + $this->santunan + $this->wakaf;
    }

    public function setJumlah(): void
    {
        $this->jumlah = $this->getJumlah();
    }

    public function scopeBerhasil($query)
    {
        return $query->whereIn('status', DonasiStatus::Berhasil());
    }
}

resources/views/exports/anggota-donasi.blade.php
<style>
  table { border-collapse: collapse; font-size: small; }
  td, th { border: 1px solid #000; padding: 5px; }
  .number { text-align: right; }
</style>

<table>
  <thead>
    <tr>
      <th>Tanggal</th>
      <th>Status</th>
      <th>Zakat</th>
      <th>Infak</th>
      <th>Santunan Yatim</th>
      <th>Wakaf Tunai</th>
      <th>Jumlah</th>
      <th>Keterangan</th>
    </tr>
  </thead>
  <tbody>
    @foreach ($list_donasi as $donasi)
      <tr>
        <td>{{ $donasi->tanggal->format('d-m-Y') }}</td>
        <td @if ($color = $donasi->status_enum->getColor())
          style="color: {{ $color }}"
          @endif>
          {{ $donasi->status_enum->description }}
        </td>
        <td class="number">{{ $donasi->zakat }}</td>
        <td class="number">{{ $donasi->infak }}</td>
        <td class="number">{{ $donasi->santunan }}</td>
        <td class="number">{{ $donasi->wakaf }}</td>
        <td class="number">{{ $donasi->jumlah }}</td>
        <td>{!! nl2br(e($donasi->keterangan)) !!}</td>
      </tr>
    @endforeach
  </tbody>
</table>

resources/views/exports/distribusi.blade.php
<style>
  table { border-collapse: collapse; font-size: small; }
  td, th { border: 1px solid #000; padding: 5px; }
  .number { text-align: right; }
</style>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>tanggal</th>
      <th>item</th>
      <th>dana</th>
      <th>mustahik</th>
      <th>nik</th>
      <th>asnaf</th>
      <th>bidang</th>
      <th>sdg</th>
      <th>nominal</th>
    </tr>
  </thead>
  <tbody>
    @foreach ($list_distribusi as $distribusi)
      <tr>
        <td>{{ $distribusi->id }}</td>
        <td>{{ $distribusi->tanggal->format('Y-m-d H:i:s') }}</td>
        <td>{{ $distribusi->item }}</td>
        <td>{{ $distribusi->dana_text }}</td>
        <td>{{ $distribusi->mustahik->nama ?? '-' }}</td>
        <td>{{ $distribusi->mustahik->nik ?? '-' }}</td>
        <td>{{ $distribusi->asnaf_text ?: '-' }}</td>
        <td>{{ $distribusi->bidang_text ?: '-' }}</td>
        <td>{{ $distribusi->sdg_text ?: '-' }}</td>
        <td class="number">{{ $distribusi->nominal }}</td>
      </tr>
    @endforeach
  </tbody>
</table>

resources/views/exports/donasi.blade.php
<style>
  table { border-collapse: collapse; font-size: small; }
  td, th { border: 1px solid #000; padding: 5px; }
  .number { text-align: right; }
</style>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>nama</th>
      <th>nip</th>
      <th>tanggal</th>
      <th>status</th>
      <th>zakat</th>
      <th>infak</th>
      <th>santunan</th>
      <th>wakaf</th>
      <th>jumlah</th>
      <th>keterangan</th>
    </tr>
  </thead>
  <tbody>
    @foreach ($list_donasi as $donasi)
      <tr>
        <td>{{ $donasi->id }}</td>
        <td>{{ $donasi->muzaki->nama }}</td>
        <td>{{ $donasi->muzaki->nip }}</td>
        <td>{{ $donasi->tanggal->format('Y-m-d H:i:s') }}</td>
        <td>
          {{ $donasi->status_enum->description }}
        </td>
        <td class="number">{{ $donasi->zakat }}</td>
        <td class="number">{{ $donasi->infak }}</td>
        <td class="number">{{ $donasi->santunan }}</td>
        <td class="number">{{ $donasi->wakaf }}</td>
        <td class="number">{{ $donasi->jumlah }}</td>
        <td>{!! nl2br(e($donasi->keterangan)) !!}</td>
      </tr>
    @endforeach
  </tbody>
</table>

resources/views/exports/mustahik.blade.php
<style>
  table { border-collapse: collapse; font-size: small; }
  td, th { border: 1px solid #000; padding: 5px; }
  .number { text-align: right; }
</style>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>nama</th>
      <th>nik</th>
      <th>nrp</th>
      <th>nomor_hp</th>
      <th>asnaf</th>
      <th>id_kelurahan</th>
      <th>id_kecamatan</th>
      <th>id_kota</th>
      <th>id_provinsi</th>
      <th>nama_kelurahan</th>
      <th>nama_kecamatan</th>
      <th>nama_kota</th>
      <th>nama_provinsi</th>
      <th>alamat</th>
    </tr>
  </thead>
  <tbody>
    @foreach ($list_mustahik as $mustahik)
      <tr>
        <td>{{ $mustahik->id }}</td>
        <td>{{ $mustahik->nama }}</td>
        <td>{{ $mustahik->nik }}</td>
        <th>{{ $mustahik->nrp }}</th>
        <th>{{ $mustahik->nomor_hp }}</th>
        <th>{{ $mustahik->asnaf_text }}</th>
        <th>{{ $mustahik->id_kelurahan }}</th>
        <th>{{ $mustahik->id_kecamatan }}</th>
        <th>{{ $mustahik->id_kota }}</th>
        <th>{{ $mustahik->id_provinsi }}</th>
        <th>{{ $mustahik->nama_kelurahan }}</th>
        <th>{{ $mustahik->nama_kecamatan }}</th>
        <th>{{ $mustahik->nama_kota }}</th>
        <th>{{ $mustahik->nama_provinsi }}</th>
        <th>{{ $mustahik->alamat }}</th>
      </tr>
    @endforeach
  </tbody>
</table>

resources/views/exports/muzaki.blade.php
<style>
  table { border-collapse: collapse; font-size: small; }
  td, th { border: 1px solid #000; padding: 5px; }
  .number { text-align: right; }
</style>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>nama</th>
      <th>email</th>
      <th>nip</th>
      <th>npwp</th>
      <th>nomor_hp</th>
      <th>nomor_wa</th>
      <th>nomor_rekening</th>
    </tr>
  </thead>
  <tbody>
    @foreach ($list_muzaki as $muzaki)
      <tr>
        <td>{{ $muzaki->id }}</td>
        <td>{{ $muzaki->nama }}</td>
        <td>{{ $muzaki->email }}</td>
        <td>{{ $muzaki->nip }}</td>
        <td>{{ $muzaki->npwp }}</td>
        <td>{{ $muzaki->nomor_hp }}</td>
        <td>{{ $muzaki->nomor_wa }}</td>
        <td>{{ $muzaki->nomor_rekening }}</td>
      </tr>
    @endforeach
  </tbody>
</table>